services:
  app-fe:
    build:
      dockerfile: docker/Dockerfile.app
    ports:
      - '3000:3000'
    volumes:
      - ./react-app:/app/
    networks:
      - default
    depends_on:
      - db
    command: sh -c "mkdir /app; cd /app;npm install;npm start"
  app-be:
    build:
      dockerfile: docker/Dockerfile.app
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app
    networks:
      - default
    depends_on:
      - db
    command: sh -c "cd /app && npm install && npx sequelize db:migrate && npx nodemon app.js"
  db:
    image: "mariadb:11"
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=db-dev-root
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=posts-app-db
      - MYSQL_USER=posts-app-user
      - MYSQL_PASSWORD=posts-app-pass
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - default

networks:
  default:
    driver: bridge
